# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: copingheimer-deployment
  labels:
    app: copingheimer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: copingheimer
  template:
    metadata:
      labels:
        app: copingheimer
    spec:
      containers:
        - name: copingheimer
          image: edouard127/copingheimer:latest
          env:
            - name: ip
              value: "0.0.0.0"
          args: ["--ip=$(ip)"] # Example of how to use the env variable
          resources:
            requests:
              memory: "4096Mi"
              cpu: "750m"
            limits:
              memory: "8192Mi"
              cpu: "2000m"
          imagePullPolicy: Always