# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: copingheimer-deployment
  labels:
    app: copingheimer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: copingheimer
  template:
    metadata:
      labels:
        app: copingheimer
    spec:
      containers:
        - name: copingheimer
          image: edouard127/copingheimer:latest
          resources:
            limits:
              cpu: "8"
            requests:
              cpu: "4"
          imagePullPolicy: Always